spring:
  application:
    name: klage-oppgave-api
  main:
    banner-mode: OFF
  sleuth:
    baggage:
      remote-fields:
        - Nav-Callid
        - Nav-Consumer-Id
      correlation-fields:
        - Nav-Callid
        - Nav-Consumer-Id
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  cache:
    redis:
      time-to-live: "480m"
      key-prefix: klageoppgaveapi
  redis:
    host: klage-redis
    timeout: "10s"
  datasource:
    platform: postgresql
    url: jdbc:postgresql://${NAIS_DATABASE_KLAGE_OPPGAVE_API_KLAGE_OPPGAVE_API_HOST}:${NAIS_DATABASE_KLAGE_OPPGAVE_API_KLAGE_OPPGAVE_API_PORT}/${NAIS_DATABASE_KLAGE_OPPGAVE_API_KLAGE_OPPGAVE_API_DATABASE}
    username: ${NAIS_DATABASE_KLAGE_OPPGAVE_API_KLAGE_OPPGAVE_API_USERNAME}
    password: ${NAIS_DATABASE_KLAGE_OPPGAVE_API_KLAGE_OPPGAVE_API_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    clean-on-validation-error: true
    schemas: flyway_history_schema,klage,oppgave,kodeverk

server:
  port: 7081
  error:
    whitelabel:
      enabled: false

management:
  health:
    elasticsearch:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

SERVICE_USER_USERNAME: srvklage-saksbeh

no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
  client:
    registration:
      azure-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: https://graph.microsoft.com/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      oppgave-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: api://${OPPGAVE_APP_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      proxy-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: api://${PROXY_APP_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      app:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: https://graph.microsoft.com/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

navCallId: Nav-Callid
navConsumerId: Nav-Consumer-Id

allowed.origins:
  https://klage-oppgave.nav.no,
  https://klage-oppgave.dev.nav.no

MICROSOFT_GRAPH_URL: https://graph.microsoft.com/v1.0
UNLEASH_URL: https://unleash.nais.io/api/

KAFKA_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_SCHEMA_REGISTRY_URL: http://localhost:9093
KAFKA_GROUP_ID: klage-oppgave-api
EGENANSATT_KAFKA_TOPIC: aapen-skjermede-personer-v1
PDL_PERSON_KAFKA_TOPIC: aapen-person-pdl-dokument-v1

SERVICE_USER_PASSWORD: itest