SECURITY_TOKEN_SERVICE_REST_URL: http://localhost:8088
SERVICE_USER_USERNAME: igroup
SERVICE_USER_PASSWORD: itest
SLACK_URL: localhost:8080
SLACK_CHANNEL_ID: #none
NAIS_CLUSTER_NAME: local
AZURE_APP_WELL_KNOWN_URL: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
NORG2_API_V1_URL: local
NORG2_APIKEY: 123
OPPGAVE_APIKEY: 456
STS_APIKEY: 789
PDL_BASE_URL: local
PDL_APIKEY: 159
AXSYS_APIKEY: 357
SAF_BASE_URL: local
SAF_APP_CLIENT_ID: uu-id
nais:
  cluster:
    name: local
spring:
  redis:
    host: localhost
AIVEN_ES_SCHEME: http
AIVEN_ES_HOST: localhost
AIVEN_ES_PORT: 9200
AIVEN_ES_USE_SSL: false
AIVEN_ES_USERNAME_ADM: elasticsearch
AIVEN_ES_PASSWORD_ADM: password

NAIS_DATABASE_KABAL_API_KABAL_API_USERNAME: klage
NAIS_DATABASE_KABAL_API_KABAL_API_PASSWORD: klage
NAIS_DATABASE_KABAL_API_KABAL_API_DATABASE: kabal-api
NAIS_DATABASE_KABAL_API_KABAL_API_HOST: localhost
NAIS_DATABASE_KABAL_API_KABAL_API_PORT: 5432

AXSYS_URL: https://axsys.dev.adeo.no/v1

ROLE_KLAGE_SAKSBEHANDLER: 07add1e7-7195-4c37-828d-fdf23ec6bef1
ROLE_KLAGE_FAGANSVARLIG: 94d34f17-e325-4ed6-9667-d23041a3f40c
ROLE_KLAGE_LEDER: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
ROLE_KLAGE_MERKANTIL: 094f801c-1085-4832-9463-25bf7a1087f1
ROLE_KLAGE_FORTROLIG: 2980c598-8af7-473f-b7d1-233f785d7001
ROLE_KLAGE_STRENGT_FORTROLIG: de92036b-c350-471c-9249-753f36acd24d
ROLE_KLAGE_EGEN_ANSATT: 011af9b0-792d-4d2c-a2eb-9a59fc095002
ROLE_GOSYS_OPPGAVE_BEHANDLER: a9f5ef81-4e81-42e8-b368-0273071b64b9

OPPGAVE_URL: https://api-gw-q1.oera.no/oppgave/api/v1/oppgaver

JOARK_SERVICE_URL: http://localhost:1234
JOURNALPOST_APIKEY: none
DOKDIST_SERVICE_URL: TODO
DOKDIST_APIKEY: TODO