TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851
SECURITY_TOKEN_SERVICE_REST_URL: https://api-gw-q1.oera.no/security-token-service
PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io/graphql
PDL_SCOPE: dev-fss.pdl.pdl-api

NORG2_API_V1_URL: https://api-gw-q1.oera.no/norg2/api/v1
PROXY_APP_CLIENT_ID: c6050231-3b9f-4173-8d1e-39b7e6e3392e

OPPGAVE_APP_CLIENT_ID: bef7cd4d-e65e-41f8-a743-b643e81f2aea

OPPGAVE_URL: https://api-gw-q1.oera.no/oppgave/api/v1/oppgaver

EREG_URL: https://api-gw-q1.oera.no/ereg/api

AXSYS_URL: https://api-gw-q1.oera.no/axsys/api/v2
AXSYS_CLUSTER: dev-fss
AXSYS_NAMESPACE: org
AXSYS_APP: axsys

VEDTAK_FATTET_TOPIC: klage.vedtak-fattet.v1
DVH_STATISTIKK_TOPIC: klage.kabal-statistikk.v1

AIVEN_ES_HOST: elastic-klage-oppgave-es-nav-dev.aivencloud.com
AIVEN_ES_PORT: 26482
AIVEN_ES_SCHEME: https
AIVEN_ES_USE_SSL: true

SAF_BASE_URL: https://saf.dev-fss-pub.nais.io/
SAF_APP_CLIENT_ID: c7adbfbb-1b1e-41f6-9b7a-af9627c04998

DOKARKIV_CLIENT_ID: 972814f3-8bdf-44f8-a191-c2ed00020b54

ROLE_KLAGE_SAKSBEHANDLER: 07add1e7-7195-4c37-828d-fdf23ec6bef1
ROLE_KLAGE_FAGANSVARLIG: 94d34f17-e325-4ed6-9667-d23041a3f40c
ROLE_KLAGE_LEDER: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
ROLE_KLAGE_MERKANTIL: 094f801c-1085-4832-9463-25bf7a1087f1
ROLE_KLAGE_FORTROLIG: 2980c598-8af7-473f-b7d1-233f785d7001
ROLE_KLAGE_STRENGT_FORTROLIG: de92036b-c350-471c-9249-753f36acd24d
ROLE_KLAGE_EGEN_ANSATT: 011af9b0-792d-4d2c-a2eb-9a59fc095002

ROLE_GOSYS_OPPGAVE_BEHANDLER: a9f5ef81-4e81-42e8-b368-0273071b64b9
ROLE_ADMIN: a9f5ef81-4e81-42e8-b368-0273071b64b9

JOARK_SERVICE_URL: https://api-gw-q1.oera.no/dokarkiv/rest/journalpostapi/v1/journalpost
DOKDIST_SERVICE_URL: https://api-gw-q1.oera.no/dokdistfordeling/rest/v1/distribuerjournalpost

CLAM_AV_URL: http://clamav.clamav/scan

INFLUX_HOST: influx-klage-nav-dev.aivencloud.com
INFLUX_PORT: 26482

allowed.origins:
  https://kabal.nav.no,
  https://kabal.dev.nav.no,
  http://localhost
