spring:
  application:
    name: kabal-api
  main:
    banner-mode: OFF
  sleuth:
    baggage:
      remote-fields:
        - Nav-Callid
        - Nav-Consumer-Id
      correlation-fields:
        - Nav-Callid
        - Nav-Consumer-Id
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  cache:
    redis:
      time-to-live: "480m"
      key-prefix: klageoppgaveapi
  redis:
    host: klage-redis
    timeout: "10s"
  datasource:
    platform: postgresql
    url: jdbc:postgresql://${NAIS_DATABASE_KABAL_API_KABAL_API_HOST}:${NAIS_DATABASE_KABAL_API_KABAL_API_PORT}/${NAIS_DATABASE_KABAL_API_KABAL_API_DATABASE}
    username: ${NAIS_DATABASE_KABAL_API_KABAL_API_USERNAME}
    password: ${NAIS_DATABASE_KABAL_API_KABAL_API_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    clean-on-validation-error: true
    schemas: flyway_history_schema,klage,kodeverk
  elasticsearch:
    rest:
      uris: "${AIVEN_ES_SCHEME}://${AIVEN_ES_HOST}:${AIVEN_ES_PORT}"
      read-timeout: "10s"
      username: "${AIVEN_ES_USERNAME_ADM}"
      password: "${AIVEN_ES_PASSWORD_ADM}"
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: "${AIVEN_ES_HOST}:${AIVEN_ES_PORT}"
          use-ssl: ${AIVEN_ES_USE_SSL}
          socket-timeout: "10s"
          username: "${AIVEN_ES_USERNAME_ADM}"
          password: "${AIVEN_ES_PASSWORD_ADM}"
      repositories:
        enabled: false
  jpa:
    open-in-view: false
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: 7081
  error:
    whitelabel:
      enabled: false
  shutdown: graceful

management:
  health:
    elasticsearch:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

SERVICE_USER_USERNAME: srvklage-saksbeh

no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
  client:
    registration:
      azure-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: https://graph.microsoft.com/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      oppgave-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: api://${OPPGAVE_APP_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      saf-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: api://${SAF_APP_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      axsys-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: api://${AXSYS_CLUSTER}.${AXSYS_NAMESPACE}.${AXSYS_APP}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      axsys-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${AXSYS_CLUSTER}.${AXSYS_NAMESPACE}.${AXSYS_APP}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      proxy-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: api://${PROXY_APP_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      app:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: https://graph.microsoft.com/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

navCallId: Nav-Callid
navConsumerId: Nav-Consumer-Id

allowed.origins:
  https://klage-oppgave.nav.no,
  https://klage-oppgave.dev.nav.no

MICROSOFT_GRAPH_URL: https://graph.microsoft.com/v1.0
UNLEASH_URL: https://unleash.nais.io/api/

KAFKA_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_SCHEMA_REGISTRY_URL: http://localhost:9093
KAFKA_GROUP_ID: kabal-api
EGENANSATT_KAFKA_TOPIC: aapen-skjermede-personer-v1
PDL_PERSON_KAFKA_TOPIC: aapen-person-pdl-dokument-v1

SERVICE_USER_PASSWORD: itest