ingress: https://klage-oppgave-api.dev.nav.no
externalHosts:
  - login.microsoftonline.com
  - hooks.slack.com
  - unleash.nais.io
  - klage-fss-proxy.dev-fss-pub.nais.io
  - kafka-schema-registry.nais-q.adeo.no
  - saf.dev-fss-pub.nais.io
springProfile: dev-gcp
tenant: trygdeetaten.no
db_tier: db-custom-1-3840
db_size: 10
db_ha: true
ROLE_KLAGE_SAKSBEHANDLER: 07add1e7-7195-4c37-828d-fdf23ec6bef1
ROLE_KLAGE_FAGANSVARLIG: 94d34f17-e325-4ed6-9667-d23041a3f40c
ROLE_KLAGE_LEDER: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
ROLE_KLAGE_MERKANTIL: 094f801c-1085-4832-9463-25bf7a1087f1
ROLE_KLAGE_FORTROLIG: 2980c598-8af7-473f-b7d1-233f785d7001
ROLE_KLAGE_STRENGT_FORTROLIG: de92036b-c350-471c-9249-753f36acd24d
ROLE_KLAGE_EGEN_ANSATT: 011af9b0-792d-4d2c-a2eb-9a59fc095002
ROLE_GOSYS_OPPGAVE_BEHANDLER: a9f5ef81-4e81-42e8-b368-0273071b64b9
