ingresses:
  - https://kabal-api.dev.intern.nav.no
externalHosts:
  - host: login.microsoftonline.com
  - host: hooks.slack.com
  - host: unleash.nais.io
  - host: klage-fss-proxy.dev-fss-pub.nais.io
  - host: kafka-schema-registry.nais-q.adeo.no
  - host: saf.dev-fss-pub.nais.io
  - host: norg2.dev-fss-pub.nais.io
  - host: ereg-services-q1.dev-fss-pub.nais.io
  - host: pdl-api.dev-fss-pub.nais.io
    ports:
      - name: https
        port: 26482
        protocol: TCP
inboundApplications:
  - application: kabal-frontend
  - application: klage-dittnav-api
  - application: klage-arkiver-journalpost
  - application: kabal-behandling-creator
  - application: k9-klage
    namespace: k9saksbehandling
    cluster: dev-fss
  - application: su-se-bakover
    namespace: supstonad
    cluster: dev-fss
  - application: fpsak
    namespace: teamforeldrepenger
    cluster: dev-fss
  - application: familie-klage
    namespace: teamfamilie
    cluster: dev-gcp
springProfile: dev-gcp
tenant: trygdeetaten.no
db_tier: db-custom-1-3840
db_size: 10
db_ha: true
kafka_pool: nav-dev

adRoles:
  - name: KABAL_OPPGAVESTYRING_ALLE_ENHETER_ROLE_ID
    value: 7ad08bfe-68d4-4c84-bddd-82d8894fb36e
  - name: KABAL_MALTEKSTREDIGERING_ROLE_ID
    value: 0097d4ff-787d-4180-953a-8d60b7927f32
  - name: KABAL_SAKSBEHANDLING_ROLE_ID
    value: 07add1e7-7195-4c37-828d-fdf23ec6bef1
  - name: KABAL_FAGTEKSTREDIGERING_ROLE_ID
    value: 94d34f17-e325-4ed6-9667-d23041a3f40c
  - name: KABAL_INNSYN_EGEN_ENHET_ROLE_ID
    value: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
  - name: FORTROLIG_ROLE_ID
    value: ea930b6b-9397-44d9-b9e6-f4cf527a632a
  - name: STRENGT_FORTROLIG_ROLE_ID
    value: 5ef775f2-61f8-4283-bf3d-8d03f428aa14
  - name: EGEN_ANSATT_ROLE_ID
    value: dbe4ad45-320b-4e9a-aaa1-73cca4ee124d
  - name: KABAL_ADMIN_ROLE_ID
    value: a9f5ef81-4e81-42e8-b368-0273071b64b9

envs:
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - name: JAVA_OPTS
    value: "-Xms512m -Xmx4096m"