apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: klage-oppgave-e2e
  name: klage-oppgave-e2e
  namespace: klage
spec:
  backoffLimit: 4
  activeDeadlineSeconds: 240
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: klage-oppgave-e2e
        app: klage-oppgave-e2e
    spec:
      imagePullSecrets:
        - name: gpr-credentials
      serviceAccount: default
      serviceAccountName: default
      containers:
        - command:
            - sh
            - tests.sh
          image: docker.pkg.github.com/navikt/klage-oppgave-e2e/klage-oppgave-e2e:latest
          imagePullPolicy: IfNotPresent
          name: klage-oppgave-e2e
      dnsPolicy: ClusterFirst
      restartPolicy: Never
