ingress: https://klage-oppgave-api.intern.nav.no
externalHosts:
  - login.microsoftonline.com
  - hooks.slack.com
  - unleash.nais.io
  - klage-fss-proxy.prod-fss-pub.nais.io
  - kafka-schema-registry.nais.adeo.no
springProfile: prod-gcp
tenant: nav.no
db_tier: db-custom-4-15360
db_size: 10
db_ha: true
