ingresses:
  - https://kabal-api.intern.nav.no
externalHosts:
  - host: login.microsoftonline.com
  - host: hooks.slack.com
  - host: unleash.nais.io
  - host: klage-fss-proxy.prod-fss-pub.nais.io
  - host: kafka-schema-registry.nais.adeo.no
  - host: saf.prod-fss-pub.nais.io
  - host: norg2.prod-fss-pub.nais.io
  - host: ereg-services.prod-fss-pub.nais.io
  - host: pdl-api.prod-fss-pub.nais.io
    ports:
      - name: https
        port: 26482
        protocol: TCP
inboundApplications:
  - application: kabal-frontend
  - application: klage-dittnav-api
  - application: klage-arkiver-journalpost
  - application: k9-klage
    namespace: k9saksbehandling
    cluster: prod-fss
  - application: su-se-bakover
    namespace: supstonad
    cluster: prod-fss
  - application: fpsak
    namespace: teamforeldrepenger
    cluster: prod-fss
  - application: familie-klage
    namespace: teamfamilie
    cluster: prod-gcp
springProfile: prod-gcp
tenant: nav.no
db_tier: db-custom-4-15360
db_size: 10
db_ha: true
kafka_pool: nav-prod
KABAL_OPPGAVESTYRING_ALLE_ENHETER: 1c006e8b-c667-4622-9df7-43ed2fd494d6
KABAL_MALTEKSTREDIGERING: 95c25ca2-e3e9-423e-a55f-9bc327c29f96
KABAL_SAKSBEHANDLING: 2b671b60-9650-4839-9139-40999bbb0f71
KABAL_FAGTEKSTREDIGERING: 1edfbdf1-c1bc-4dc6-9cab-4fff1cb7e2a8
KABAL_OPPGAVESTYRING_EGEN_ENHET: e9de217a-7244-45ac-8a06-1994905d7964
KABAL_ADMIN: cd78b8e8-73a3-4fb6-8234-7bebb5e5b9e9

envs:
  - name: JAVA_OPTS
    value: "-Xms512m -Xmx4096m"
